### ISSUE TITLE
Query-based requests

### ISSUE THREAD

**Issue by itsHenry35** [alist-org/gofakes3#1]
Support query-based auth signature

**Comment by itsHenry35** [comment]
https://github.com/alist-org/gofakes3/commit/5799d51f4555e2f3dbd3bfb93685a3b867754150

**Comment by KevinWang15** [comment]
@itsHenry35 Great job! I just opened an issue on https://github.com/rclone/gofakes3/issues/5 then I found your work.

Have you considered submitting a pull request to the upstream repository (https://github.com/rclone/gofakes3) too?
Your contributions could also make `rclone serve s3` better. 👍👍👍
